### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by cborne** [timovn/C-LX-RSS#3]
Bonjour,

Sur une instance neuve, chargement d'un opml de 94 flux, découverte du logiciel en passant à une vue façon netvibes, retour sous la forme classique de vue, plus rien ne fonctionne au clic. Dans la version mobile, pas mieux aucun flux ne s'affiche, rien ne peut-être sélectionné. 

Par quoi je peux commencer pour t'aider ? 

Cyrille

**Comment by timovn** [comment]
Salut,

Si je comprends bien, tu as codé une façon de mettre la disposition au format Netvibes, donc en bloc plutôt qu’en liste ?

Si les blocs représentent un seul post, c’est juste une question de CSS. Si les blocs représentent un site/flux, avec chacun leur sous-liste… il faut toucher au JS en plus du CSS.

Le code PHP ne gère que la liste latérale des différents sites (jusqu’à ce que je change ça aussi).
Normalement, quelque soit la vue que tu veux, tu peux le faire (mais pas de façon optimisée) sans y toucher.

**Comment by cborne** [comment]
Je n'ai absolument rien codé du tout. Faut que je réessaie parce que c'est un peu du déterrage :D

**Comment by timovn** [comment]
(Pardon du retard)

Ce lecteur RSS ne propose pas de vue "façon netvibes" pour les flux, c’est pour ça que ça me surprend.
